[2025-02-18T11:02:33.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T11:02:33.137+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_news_scraper.get_and_parse_articles manual__2025-02-18T11:02:28.040747+00:00 [queued]>
[2025-02-18T11:02:33.146+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_news_scraper.get_and_parse_articles manual__2025-02-18T11:02:28.040747+00:00 [queued]>
[2025-02-18T11:02:33.147+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-02-18T11:02:33.160+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_and_parse_articles> on 2025-02-18 11:02:28.040747+00:00
[2025-02-18T11:02:33.168+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T11:02:33.170+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_news_scraper', 'get_and_parse_articles', 'manual__2025-02-18T11:02:28.040747+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpl1_9aby2']
[2025-02-18T11:02:33.173+0000] {standard_task_runner.py:72} INFO - Started process 474 to run task
[2025-02-18T11:02:33.174+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask get_and_parse_articles
[2025-02-18T11:02:33.221+0000] {task_command.py:467} INFO - Running <TaskInstance: google_news_scraper.get_and_parse_articles manual__2025-02-18T11:02:28.040747+00:00 [running]> on host 9546a27fb76d
[2025-02-18T11:02:33.291+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_news_scraper' AIRFLOW_CTX_TASK_ID='get_and_parse_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T11:02:28.040747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T11:02:28.040747+00:00'
[2025-02-18T11:02:33.293+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T11:02:33.294+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T11:02:33.295+0000] {logging_mixin.py:190} INFO - Current task name:get_and_parse_articles state:running start_date:2025-02-18 11:02:33.138974+00:00
[2025-02-18T11:02:33.296+0000] {logging_mixin.py:190} INFO - Dag name:google_news_scraper and current dag run status:running
[2025-02-18T11:02:33.296+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T11:02:35.180+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag2.py", line 34, in get_and_parse_articles
    articles = parse_google_news(html)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/google_news_scraper.py", line 177, in parse_google_news
    article_counter = get_next_article_id()  # Initialize counter from the last ID in the DB
                      ^^^^^^^^^^^^^^^^^^^
NameError: name 'get_next_article_id' is not defined
[2025-02-18T11:02:35.217+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-18T11:02:35.219+0000] {logging_mixin.py:190} INFO - Task start:2025-02-18 11:02:33.138974+00:00 end:2025-02-18 11:02:35.217535+00:00 duration:2.078561
[2025-02-18T11:02:35.220+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_and_parse_articles> dag:<DAG: google_news_scraper> dagrun:<DagRun google_news_scraper @ 2025-02-18 11:02:28.040747+00:00: manual__2025-02-18T11:02:28.040747+00:00, state:running, queued_at: 2025-02-18 11:02:28.053234+00:00. externally triggered: True>
[2025-02-18T11:02:35.221+0000] {logging_mixin.py:190} INFO - Failure caused by name 'get_next_article_id' is not defined
[2025-02-18T11:02:35.221+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=google_news_scraper, task_id=get_and_parse_articles, run_id=manual__2025-02-18T11:02:28.040747+00:00, execution_date=20250218T110228, start_date=20250218T110233, end_date=20250218T110235
[2025-02-18T11:02:35.250+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T11:02:35.251+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 74 for task get_and_parse_articles (name 'get_next_article_id' is not defined; 474)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag2.py", line 34, in get_and_parse_articles
    articles = parse_google_news(html)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/google_news_scraper.py", line 177, in parse_google_news
    article_counter = get_next_article_id()  # Initialize counter from the last ID in the DB
                      ^^^^^^^^^^^^^^^^^^^
NameError: name 'get_next_article_id' is not defined
[2025-02-18T11:02:35.289+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T11:02:35.311+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T11:02:35.317+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
