[2025-02-16T14:55:22.860+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T14:55:22.873+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_news_scraper.load_config manual__2025-02-16T14:45:09.623833+00:00 [queued]>
[2025-02-16T14:55:22.879+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_news_scraper.load_config manual__2025-02-16T14:45:09.623833+00:00 [queued]>
[2025-02-16T14:55:22.879+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-02-16T14:55:22.892+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_config> on 2025-02-16 14:45:09.623833+00:00
[2025-02-16T14:55:22.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T14:55:22.901+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2025-02-16T14:55:22.903+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_news_scraper', 'load_config', 'manual__2025-02-16T14:45:09.623833+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpeky8k0t_']
[2025-02-16T14:55:22.904+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask load_config
[2025-02-16T14:55:22.943+0000] {task_command.py:467} INFO - Running <TaskInstance: google_news_scraper.load_config manual__2025-02-16T14:45:09.623833+00:00 [running]> on host 1988608d196d
[2025-02-16T14:55:23.013+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_news_scraper' AIRFLOW_CTX_TASK_ID='load_config' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T14:45:09.623833+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T14:45:09.623833+00:00'
[2025-02-16T14:55:23.015+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-16T14:55:23.015+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-16T14:55:23.015+0000] {logging_mixin.py:190} INFO - Current task name:load_config state:running start_date:2025-02-16 14:55:22.874102+00:00
[2025-02-16T14:55:23.016+0000] {logging_mixin.py:190} INFO - Dag name:google_news_scraper and current dag run status:running
[2025-02-16T14:55:23.016+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T14:55:23.017+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag2.py", line 10, in load_config
    with open('config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[2025-02-16T14:55:23.025+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-16T14:55:23.025+0000] {logging_mixin.py:190} INFO - Task start:2025-02-16 14:55:22.874102+00:00 end:2025-02-16 14:55:23.024678+00:00 duration:0.150576
[2025-02-16T14:55:23.026+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_config> dag:<DAG: google_news_scraper> dagrun:<DagRun google_news_scraper @ 2025-02-16 14:45:09.623833+00:00: manual__2025-02-16T14:45:09.623833+00:00, state:running, queued_at: 2025-02-16 14:45:09.642975+00:00. externally triggered: True>
[2025-02-16T14:55:23.026+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'config.json'
[2025-02-16T14:55:23.026+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=google_news_scraper, task_id=load_config, run_id=manual__2025-02-16T14:45:09.623833+00:00, execution_date=20250216T144509, start_date=20250216T145522, end_date=20250216T145523
[2025-02-16T14:55:23.046+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T14:55:23.047+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task load_config ([Errno 2] No such file or directory: 'config.json'; 315)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag2.py", line 10, in load_config
    with open('config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[2025-02-16T14:55:23.079+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-16T14:55:23.102+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T14:55:23.107+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
